# Generated by Django 3.2.12 on 2023-09-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='name',
        ),
        migrations.AddField(
            model_name='bird',
            name='catalogue_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='cnt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='gen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='group',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='loc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='rec',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='sex',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='sound_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='sp',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='ssp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bird',
            name='stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='audio_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
