# Generated by Django 3.2.12 on 2023-09-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20230921_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='catalogue_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='cnt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='gen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='group',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='loc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='rec',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='sound_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='sp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
