# Generated by Django 3.2.12 on 2023-09-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20230921_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bird',
            name='lng',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
