# Generated by Django 3.2.12 on 2023-09-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20230921_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='bird',
            name='image_url',
        ),
        migrations.AddField(
            model_name='bird',
            name='audio',
            field=models.FileField(default=3000, upload_to='bird_audios/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bird',
            name='image',
            field=models.ImageField(default=3000, upload_to='bird_images/'),
            preserve_default=False,
        ),
    ]
